In [4]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

import urllib3
urllib3.disable_warnings()

data=[]
html_text= requests.get("https://hmfw.ap.gov.in/covid_dashboard.aspx",verify=False).text
soup = BeautifulSoup(html_text,"lxml")

table = soup.find('table', attrs={'class':'table table-bordered table-striped'}) 
rows = table.find_all('tr')

for row in rows:
    cols = row.findAll('td')
    cols = [ele.text.strip() for ele in cols]
    data.append([ele for ele in cols if ele]) 
    
df= pd.DataFrame(data,columns=['District','ConfirmedCases','Cured','Deceased'])
df=df.drop(df.index[[0]])
df

           District ConfirmedCases    Cured Deceased
1        Ananthapur         157250   156046     1091
2          Chittoor         239229   235286     1859
3     East Godavari         286877   283149     1262
4            Guntur         173171   170923     1186
5            Kadapa         113061   111902      631
6           Krishna         114473   111044     1328
7           Kurnool         123854   122919      850
8           Nellore         141112   137967     1010
9          Prakasam         134294   131023     1054
10       Srikakulam         122217   121054      779
11    Visakhapatnam         155293   153755     1106
12     Vizianagaram          82520    81614      669
13    West Godavari         175079   172679     1086
14   Total AP Cases        2018430  1989361    13911
15     Other States           2461     2461        0
16  Other Countries            434      434        0
17            Total        2021325  1992256    13911